
--CONVERT FROM EPOCH TO DATETIME:

DECLARE @Epoch2Convert AS BIGINT = 1354320000

SELECT dateadd(SS,CONVERT(BIGINT, @Epoch2Convert), CAST('1970-01-01 00:00:00' AS DATETIME)) as myDateTime;

---CONVERT FROM DATETIME TO EPOCH

DECLARE @Date2Convert AS DATETIME = GETDATE()

SELECT CAST(datediff(ss, 'Jan 01 1970', @Date2Convert) AS BIGINT) as myEpochDate;
