ALTER AVAILABILITY GROUP [AG NAME]  
 MODIFY REPLICA ON  
N'[Server Name 1]' WITH   
(SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY));  

ALTER AVAILABILITY GROUP [MAKYBTT220P_AG]  
 MODIFY REPLICA ON  
N'[Server Name 1]' WITH   
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://[Server Name 1].maky.midam.farm:1433'));  
  
ALTER AVAILABILITY GROUP [MAKYBTT220P_AG]  
 MODIFY REPLICA ON  
N'[Server Name 2]' WITH   
(SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY));  

ALTER AVAILABILITY GROUP [MAKYBTT220P_AG]  
 MODIFY REPLICA ON  
N'[Server Name 2]' WITH   
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://[Server Name 2].maky.midam.farm:1433'));  
  
ALTER AVAILABILITY GROUP [MAKYBTT220P_AG]   
MODIFY REPLICA ON  
N'[Server Name 1]' WITH   
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('[Server Name 2]','[Server Name 1]')));  
  
ALTER AVAILABILITY GROUP [MAKYBTT220P_AG]   
MODIFY REPLICA ON  
N'[Server Name 2]' WITH   
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('[Server Name 1]','[Server Name 2]')));  
GO  
